scraper:
  vinted:
    scraping-interval-millisec: 1000000
    address: https://jobs.lever.co/vinted/?team=Engineering
    sourceEmailAddress: XXXXXXXX
    password: XXXXXXXX
    targetEmailAddress: XXXXXXXX
    filename: Job_Postings.json