spedlite:
  email:
    inbox-check-interval-millisec: 600000
    address: https://jobs.lever.co/vinted?team=Engineering
    password: moliak6418

#    protocol: imaps
#    host: ajeras.serveriai.lt
#    port: 993
#    inbox: Inbox
#    success-folder: Success
#    fail-folder: Failed



